const userTypes = {
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  USER_ERROR: "USER_ERROR",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
};

export default userTypes;
